### ISSUE TITLE
Layout fixes

### ISSUE THREAD

**Issue by xmonkx** [DexterHuang/CyberCodeOnline#1099]
Is it possible to place body modificator for langs to provide some fixes suitable for the language? Are desktop and mobile app styles the same files?

Few examples: 

``` scss
.rus {
  .display-font,
  .markdown-body code,
  .markdown-body h1,
  .markdown-body h2,
  .markdown-body h3,
  .markdown-body h4,
  .markdown-body kbd,
  .markdown-body pre {
    /* can't render clearly fonts without cyrillic support. especially desktop version. issue preview: https://i.imgur.com/DCExxJW.png   */
    font-family: "Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif!important;
    &.capitalize {
      /* it's weird to capitalise every word for russians */
      text-transform: unset;
    }
  }
  /* extra class for chat  */
  .chat-input {
    /* reduce width of send button text. issue preview https://i.imgur.com/QLBoXPH.png  */
    .text-xs {
      font-size: .55rem;
    }
  }
}
```

and many others...
